import { EntitlementItem, BundleOffer, ProjectConfig } from '../types/entitlement';

function capitalize(s: string): string {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .split('_')
    .filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function escapeVerseString(str: string): string {
  return (str || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
}

export function generateVerseCode(
  entitlements: EntitlementItem[],
  bundles: BundleOffer[] = [],
  config: ProjectConfig
): string {
  const timestamp = new Date().toISOString();
  const infoModule = config.infoModuleName || 'ManagedEntitlementInfo';
  const entModule = config.entitlementsModuleName || 'ManagedEntitlements';
  const priceModule = config.pricesModuleName || 'ManagedTransactionPrices';
  const offersModule = config.offersModuleName || 'ManagedOffers';
  const deviceClass = config.deviceClassName || 'managed_transactions_device';
  const assetFolder = config.assetFolderName || 'EntitlementIcons';

  // Helper to format texture path
  const formatTexture = (textureStr: string, fallbackKey: string): string => {
    if (!textureStr || !textureStr.trim()) {
      return `${assetFolder}.${toPascalCase(fallbackKey)}`;
    }
    const trimmed = textureStr.trim();
    return trimmed;
  };

  let out = '';

  // 1. Imports
  out += `# ═══════════════════════════════════════════════════════════════════════════\n`;
  out += `#  ${config.targetVerseFileName || 'managed_transactions.verse'}\n`;
  out += `#  In-Island Transactions Architecture | Generated by ADEPT Interactive\n`;
  out += `#  Timestamp: ${timestamp}\n`;
  out += `# ═══════════════════════════════════════════════════════════════════════════\n\n`;

  out += `using { /Fortnite.com/Devices }\n`;
  out += `using { /Fortnite.com/Marketplace }\n`;
  out += `using { /Fortnite.com/Playspaces }\n`;
  out += `using { /UnrealEngine.com/Temporary/Diagnostics }\n`;
  out += `using { /Verse.org/Assets }\n`;
  out += `using { /Verse.org/Simulation }\n\n`;

  // 2. Localized Message Info Module
  out += `# ---------------------------------------------------------------------------\n`;
  out += `#  LOCALIZED ENTITLEMENT METADATA\n`;
  out += `# ---------------------------------------------------------------------------\n`;
  out += `${infoModule}<public> := module:\n`;

  for (const item of entitlements) {
    const modName = toPascalCase(item.verseKey);
    out += `    ${modName}<public> := module:\n`;
    out += `        Name<public><localizes>:message = "${escapeVerseString(item.name)}"\n`;
    out += `        Description<public><localizes>:message = "${escapeVerseString(item.description || item.name)}"\n`;
    out += `        ShortDescription<public><localizes>:message = "${escapeVerseString(item.shortDescription || item.name)}"\n`;
    if (item.flags.paidRandomItem && item.flags.paidRandomItemOdds) {
      out += `        DropOdds<public><localizes>:message = "${escapeVerseString(item.flags.paidRandomItemOdds)}"\n`;
    }
    out += `\n`;
  }

  // Add country codes helper
  out += `    # ISO-3166-1 A-2 Country Codes for Optional Age & Region Gating\n`;
  out += `    CountryCodes<public> := module:\n`;
  out += `        UnitedStatesOfAmerica<public>:string = "US"\n`;
  out += `        Canada<public>:string = "CA"\n`;
  out += `        UnitedKingdom<public>:string = "GB"\n`;
  out += `        Germany<public>:string = "DE"\n`;
  out += `        France<public>:string = "FR"\n`;
  out += `        Japan<public>:string = "JP"\n`;
  out += `        Australia<public>:string = "AU"\n\n`;

  // 3. Entitlements Module
  out += `# ---------------------------------------------------------------------------\n`;
  out += `#  ENTITLEMENT DEFINITIONS\n`;
  out += `# ---------------------------------------------------------------------------\n`;
  out += `${entModule}<public> := module:\n`;
  out += `    using {${infoModule}}\n\n`;
  out += `    # Abstract base entitlement class for this island's transaction system\n`;
  out += `    basic_entitlement<public> := class<abstract><castable>(entitlement){}\n\n`;

  for (const item of entitlements) {
    const modName = toPascalCase(item.verseKey);
    const className = `${item.verseKey.toLowerCase()}_entitlement`;
    const textureRef = formatTexture(item.iconTexture, item.verseKey);

    out += `    ${className}<public> := class<concrete>(basic_entitlement):\n`;
    out += `        var Name<override>:message = ${modName}.Name\n`;
    out += `        var Description<override>:message = ${modName}.Description\n`;
    out += `        var ShortDescription<override>:message = ${modName}.ShortDescription\n`;
    out += `        var Icon<override>:texture = ${textureRef}\n`;
    out += `        PaidRandomItem<override>:logic = ${item.flags.paidRandomItem ? 'true' : 'false'}\n`;
    out += `        PaidArea<override>:logic = ${item.flags.paidArea ? 'true' : 'false'}\n`;
    out += `        Consumable<override>:logic = ${item.itemType === 'consumable' ? 'true' : 'false'}\n`;
    out += `        MaxCount<override>:int = ${item.itemType === 'consumable' ? item.maxCount : 1}\n`;
    out += `        ConsequentialToGameplay<override>:logic = ${item.flags.consequentialToGameplay ? 'true' : 'false'}\n\n`;
  }

  // 4. Prices Module
  out += `# ---------------------------------------------------------------------------\n`;
  out += `#  V-BUCKS PRICING TABLE (Constants)\n`;
  out += `# ---------------------------------------------------------------------------\n`;
  out += `${priceModule}<public> := module:\n`;
  for (const item of entitlements) {
    const priceVar = `${item.verseKey.toLowerCase()}_price`;
    out += `    ${priceVar}<public>:float = ${item.priceVBucks.toFixed(1)}\n`;
  }
  for (const bundle of bundles) {
    const priceVar = `${bundle.verseKey.toLowerCase()}_price`;
    out += `    ${priceVar}<public>:float = ${bundle.priceVBucks.toFixed(1)}\n`;
  }
  out += `\n`;

  // 5. Offers Module
  out += `# ---------------------------------------------------------------------------\n`;
  out += `#  STORE OFFERS\n`;
  out += `# ---------------------------------------------------------------------------\n`;
  out += `${offersModule}<public> := module:\n`;
  out += `    using {${infoModule}}\n`;
  out += `    using {${entModule}}\n`;
  out += `    using {${priceModule}}\n\n`;

  for (const item of entitlements) {
    const offerClass = `${item.verseKey.toLowerCase()}_offer`;
    const entClass = `${item.verseKey.toLowerCase()}_entitlement`;
    const priceVar = `${item.verseKey.toLowerCase()}_price`;
    const modName = toPascalCase(item.verseKey);
    const textureRef = formatTexture(item.iconTexture, item.verseKey);

    out += `    ${offerClass}<public> := class(entitlement_offer):\n`;
    out += `        var Name<override>:message = ${modName}.Name\n`;
    out += `        var Description<override>:message = ${modName}.Description\n`;
    out += `        var ShortDescription<override>:message = ${modName}.ShortDescription\n`;
    out += `        var Icon<override>:texture = ${textureRef}\n`;
    out += `        EntitlementType<override>:concrete_subtype(entitlement) = ${entClass}\n`;
    out += `        Price<override>:price_dimension = MakePriceVBucks(${priceVar})\n`;

    // Optional age gating on offer
    if (item.ageAndRegion.enabled) {
      out += `\n        # Age & Region Gating\n`;
      out += `        GetMinPurchaseAge<override>(CountryCode:string, SubdivisionCode:string, PlatformFamily:string)<decides><computes>:int =\n`;
      if (item.ageAndRegion.allowedCountryCodes.length > 0) {
        const countryChecks = item.ageAndRegion.allowedCountryCodes
          .map(c => `CountryCode = "${c}"`)
          .join(' or ');
        out += `            ${countryChecks}\n`;
      }
      out += `            return ${item.ageAndRegion.minAge}\n`;
    }

    out += `\n`;
  }

  for (const bundle of bundles) {
    const bundleClass = `${bundle.verseKey.toLowerCase()}_offer`;
    const priceVar = `${bundle.verseKey.toLowerCase()}_price`;
    const modName = toPascalCase(bundle.verseKey);
    const textureRef = formatTexture(bundle.iconTexture, bundle.verseKey);

    out += `    ${bundleClass}<public> := class(bundle_offer):\n`;
    out += `        var Name<override>:message = ${modName}.Name\n`;
    out += `        var Description<override>:message = ${modName}.Description\n`;
    out += `        var ShortDescription<override>:message = ${modName}.ShortDescription\n`;
    out += `        var Icon<override>:texture = ${textureRef}\n`;
    out += `        Price<override>:price_dimension = MakePriceVBucks(${priceVar})\n`;
    out += `        Offers<override>:[]tuple(offer, int) = array:\n`;
    for (const bItem of bundle.items) {
      const matchedEnt = entitlements.find(e => e.id === bItem.entitlementId);
      const itemKey = matchedEnt ? matchedEnt.verseKey : bItem.entitlementId;
      const offerClass = `${itemKey.toLowerCase()}_offer`;
      out += `            (${offerClass}{}, ${bItem.quantity})\n`;
    }
    out += `\n`;
  }

  // 6. Creative Device Class
  out += `# ---------------------------------------------------------------------------\n`;
  out += `#  TRANSACTIONS & ENTITLEMENT MANAGER CREATIVE DEVICE\n`;
  out += `# ---------------------------------------------------------------------------\n`;
  out += `${deviceClass} := class(creative_device):\n\n`;

  out += `    # @editable Buttons to trigger direct purchases in-world\n`;
  out += `    @editable\n`;
  out += `    PurchaseButtons : []button_device = array{}\n\n`;

  out += `    # @editable Mutator Zones to prompt or restrict paid areas\n`;
  out += `    @editable\n`;
  out += `    PaidAreaZones : []mutator_zone_device = array{}\n\n`;

  // Dynamic Custom Signal Events for each item
  out += `    # --- Custom Signal Events ---\n`;
  for (const item of entitlements) {
    const eventName = `${toPascalCase(item.verseKey)}_PurchasedEvent`;
    out += `    ${eventName}<public>:event(player) = event(player){}\n`;
  }
  out += `\n`;

  // OnBegin Lifecycle
  out += `    OnBegin<override>()<suspends>:void =\n`;
  out += `        Print("[${deviceClass}] Initializing In-Island Transactions...")\n`;
  out += `        GetPlayspace().PlayerAddedEvent().Subscribe(OnPlayerAdded)\n\n`;
  out += `        # Subscribe existing players\n`;
  out += `        for (Player : GetPlayspace().GetPlayers()):\n`;
  out += `            OnPlayerAdded(Player)\n\n`;
  out += `        # Wire purchase buttons\n`;
  out += `        for (Button : PurchaseButtons):\n`;
  out += `            Button.InteractedWithEvent.Subscribe(OnGenericButtonInteracted)\n\n`;
  out += `        # Wire paid zone entries\n`;
  out += `        for (Zone : PaidAreaZones):\n`;
  out += `            Zone.AgentEntersEvent.Subscribe(OnGenericAgentEnteredZone)\n\n`;

  // Player Added & Purchases Changed Listener
  out += `    OnPlayerAdded(Player:player):void =\n`;
  out += `        Print("[${deviceClass}] Player joined: setting up entitlement change listener")\n`;
  out += `        GetEntitlementsChangedEvent(Player, ${entModule}.basic_entitlement).Subscribe(OnPurchasesChanged)\n`;
  out += `        spawn{ ValidatePreviousPurchases(Player) }\n\n`;

  // Authoritative Purchases Changed Handler
  out += `    OnPurchasesChanged(Player:player, EntitlementChanges:[]entitlement_change(entitlement)):void =\n`;
  out += `        Print("[${deviceClass}] Entitlements changed for player!")\n`;
  out += `        for (EntChange : EntitlementChanges, Ent := EntChange.Entitlement):\n`;
  out += `            if (EntChange.Quantity > 0):\n`;
  out += `                Print("[${deviceClass}] Processing positive entitlement grant: {EntChange.Quantity}")\n`;

  for (const item of entitlements) {
    const entClass = `${entModule}.${item.verseKey.toLowerCase()}_entitlement`;
    const funcName = `Process${toPascalCase(item.verseKey)}Purchase`;
    out += `                if (${entClass}[Ent]):\n`;
    out += `                    ${funcName}(Player, EntChange.Quantity)\n`;
  }

  out += `\n`;

  // Individual Processing Functions
  for (const item of entitlements) {
    const funcName = `Process${toPascalCase(item.verseKey)}Purchase`;
    const entClass = `${entModule}.${item.verseKey.toLowerCase()}_entitlement`;
    const eventName = `${toPascalCase(item.verseKey)}_PurchasedEvent`;

    out += `    # Handler for: ${item.name} (${item.verseKey})\n`;
    out += `    ${funcName}(Player:player, Quantity:int):void =\n`;
    out += `        Print("[${deviceClass}] Granted ${item.name} x{Quantity}")\n`;
    out += `        ${eventName}.Signal(Player)\n`;

    if (item.itemType === 'consumable' && item.autoConsume) {
      out += `        # Auto-consume consumable item\n`;
      out += `        spawn{ AutoConsume${toPascalCase(item.verseKey)}(Player, Quantity) }\n`;
    }

    out += `\n`;

    // Auto-consumption async helper
    if (item.itemType === 'consumable' && item.autoConsume) {
      out += `    AutoConsume${toPascalCase(item.verseKey)}(Player:player, Quantity:int)<suspends>:void =\n`;
      out += `        Result := ConsumeEntitlement(Player, ${entClass}, ?Count := Quantity)\n`;
      out += `        if (Result?):\n`;
      out += `            Print("[${deviceClass}] Successfully consumed ${item.verseKey} x{Quantity}")\n`;
      out += `        else:\n`;
      out += `            Print("[${deviceClass}] Failed to consume ${item.verseKey}")\n\n`;
    }
  }

  // Interactive Purchase Prompts (BuyOffer)
  out += `    # --- Interactive Purchase Triggers ---\n`;
  for (const item of entitlements) {
    const offerClass = `${offersModule}.${item.verseKey.toLowerCase()}_offer`;
    const promptFuncName = `PromptBuy${toPascalCase(item.verseKey)}`;

    out += `    ${promptFuncName}(Player:player):void =\n`;
    out += `        spawn{ ExecuteBuy${toPascalCase(item.verseKey)}(Player) }\n\n`;

    out += `    ExecuteBuy${toPascalCase(item.verseKey)}(Player:player)<suspends>:void =\n`;
    out += `        Offer := ${offerClass}{}\n`;
    out += `        Print("[${deviceClass}] Prompting purchase for ${item.name}...")\n`;
    out += `        Result := BuyOffer(Player, Offer)\n`;
    out += `        if (Result?):\n`;
    out += `            Print("[${deviceClass}] Purchase dialog completed for ${item.name}")\n`;
    out += `        else:\n`;
    out += `            Print("[${deviceClass}] Player cancelled or dialog dismissed for ${item.name}")\n\n`;
  }

  // Generic Button & Zone event callbacks
  out += `    OnGenericButtonInteracted(Agent:agent):void =\n`;
  out += `        if (Player := player[Agent]):\n`;
  out += `            Print("[${deviceClass}] Generic button clicked by player")\n\n`;

  out += `    OnGenericAgentEnteredZone(Agent:agent):void =\n`;
  out += `        if (Player := player[Agent]):\n`;
  out += `            Print("[${deviceClass}] Player entered paid zone")\n\n`;

  // Validate Previous Purchases for Durables on Rejoin
  out += `    # --- Re-Join / Durable Ownership Restoration ---\n`;
  out += `    ValidatePreviousPurchases(Player:player)<suspends>:void =\n`;
  out += `        Print("[${deviceClass}] Validating previous durable purchases for player...")\n`;

  for (const item of entitlements) {
    if (item.itemType === 'durable') {
      const entClass = `${entModule}.${item.verseKey.toLowerCase()}_entitlement`;
      const eventName = `${toPascalCase(item.verseKey)}_PurchasedEvent`;
      out += `        Purchased_${item.verseKey} := GetPurchasedEntitlements(Player, ${entClass})\n`;
      out += `        if (Owned := Purchased_${item.verseKey}[0], Owned(1) > 0):\n`;
      out += `            Print("[${deviceClass}] Restored active durable: ${item.name}")\n`;
      out += `            ${eventName}.Signal(Player)\n`;
    }
  }

  out += `\n`;

  return out;
}
