import { EntitlementItem, BundleOffer, ProjectConfig } from '../types/entitlement';

function capitalize(s: string): string {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .split('_')
    .filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function escapeVerseString(str: string): string {
  return (str || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
}

export function generateVerseCode(
  entitlements: EntitlementItem[],
  bundles: BundleOffer[] = [],
  config: ProjectConfig
): string {
  const timestamp = new Date().toISOString();
  const infoModule = config.infoModuleName || 'EntitlementInfo';
  const entModule = config.entitlementsModuleName || 'Entitlements';
  const priceModule = config.pricesModuleName || 'TransactionPrices';
  const offersModule = config.offersModuleName || 'Offers';
  const deviceClass = config.deviceClassName || 'in_island_transactions';
  const assetFolder = config.assetFolderName || 'EntitlementIcons';

  // Helper to format texture path
  const formatTexture = (textureStr: string, fallbackKey: string): string => {
    if (!textureStr || !textureStr.trim()) {
      return `${assetFolder}.${toPascalCase(fallbackKey)}`;
    }
    const trimmed = textureStr.trim();
    if (!trimmed.includes('.')) {
      return `${assetFolder}.${trimmed}`;
    }
    return trimmed;
  };

  let out = '';

  // 1. Header & Imports
  out += `# ====================================================================\n`;
  out += `# UEFN In-Island Transactions & Entitlement Manager\n`;
  out += `# Generated by ADEPT Interactive Entitlement Manager\n`;
  out += `# Documentation: https://fn.gg/z38 | Generated at: ${timestamp}\n`;
  out += `# ====================================================================\n\n`;

  out += `using { /Fortnite.com/Devices }\n`;
  out += `using { /Fortnite.com/Marketplace }\n`;
  out += `using { /UnrealEngine.com/Temporary/Diagnostics }\n`;
  out += `using { /Verse.org/Assets }\n`;
  out += `using { /Verse.org/Simulation }\n\n`;

  // 2. EntitlementInfo Module
  out += `# ====================================================================\n`;
  out += `# 1. Entitlement & Offer Localization Info\n`;
  out += `# ====================================================================\n`;
  out += `${infoModule}<public> := module:\n\n`;

  for (const item of entitlements) {
    const moduleName = toPascalCase(item.verseKey);
    out += `    ${moduleName}<public> := module:\n`;
    out += `        Name<public><localizes>:message = "${escapeVerseString(item.name)}"\n`;
    out += `        Description<public><localizes>:message = "${escapeVerseString(item.description)}"\n`;
    out += `        ShortDescription<public><localizes>:message = "${escapeVerseString(item.shortDescription || item.name)}"\n\n`;
  }

  for (const bundle of bundles) {
    const moduleName = toPascalCase(bundle.verseKey);
    out += `    ${moduleName}<public> := module:\n`;
    out += `        Name<public><localizes>:message = "${escapeVerseString(bundle.name)}"\n`;
    out += `        Description<public><localizes>:message = "${escapeVerseString(bundle.description)}"\n`;
    out += `        ShortDescription<public><localizes>:message = "${escapeVerseString(bundle.shortDescription || bundle.name)}"\n\n`;
  }

  out += `    CountryCodes<public> := module:\n`;
  out += `        Antarctica<public>:string = "AQ"\n`;
  out += `        Canada<public>:string = "CA"\n`;
  out += `        UnitedStatesOfAmerica<public>:string = "US"\n\n`;

  // 3. Entitlements Module
  out += `# ====================================================================\n`;
  out += `# 2. Entitlement Class Definitions\n`;
  out += `# ====================================================================\n`;
  out += `${entModule}<public> := module:\n`;
  out += `    using {${infoModule}}\n\n`;
  out += `    # Base abstract entitlement from which all experience entitlements inherit\n`;
  out += `    basic_entitlement<public> := class<abstract><castable>(entitlement){}\n\n`;

  for (const item of entitlements) {
    const className = `${item.verseKey}_entitlement`;
    const infoRef = `${toPascalCase(item.verseKey)}`;
    const textureRef = formatTexture(item.iconTexture, item.verseKey);
    const isConsumable = item.itemType === 'consumable';
    const isPaidRandom = item.flags.paidRandomItem;
    const isPaidArea = item.flags.paidArea;
    const isConsequential = item.flags.consequentialToGameplay;
    const maxCount = isConsumable ? Math.max(1, item.maxCount || 1) : 1;

    out += `    ${className}<public> := class<concrete>(basic_entitlement):\n`;
    out += `        var Name<override>:message = ${infoRef}.Name\n`;
    out += `        var Description<override>:message = ${infoRef}.Description\n`;
    out += `        var ShortDescription<override>:message = ${infoRef}.ShortDescription\n`;
    out += `        var Icon<override>:texture = ${textureRef}\n`;
    out += `        PaidRandomItem<override>:logic = ${isPaidRandom ? 'true' : 'false'}\n`;
    out += `        PaidArea<override>:logic = ${isPaidArea ? 'true' : 'false'}\n`;
    out += `        Consumable<override>:logic = ${isConsumable ? 'true' : 'false'}\n`;
    out += `        MaxCount<override>:int = ${maxCount}\n`;
    out += `        ConsequentialToGameplay<override>:logic = ${isConsequential ? 'true' : 'false'}\n\n`;
  }

  // 4. TransactionPrices Module
  out += `# ====================================================================\n`;
  out += `# 3. Price Constants (V-Bucks)\n`;
  out += `# ====================================================================\n`;
  out += `${priceModule}<public> := module:\n`;
  for (const item of entitlements) {
    const priceKey = toPascalCase(item.verseKey);
    const priceFloat = (item.priceVBucks || 50).toFixed(1);
    out += `    ${priceKey}<public> : float = ${priceFloat}\n`;
  }
  for (const bundle of bundles) {
    const priceKey = toPascalCase(bundle.verseKey);
    const priceFloat = (bundle.priceVBucks || 100).toFixed(1);
    out += `    ${priceKey}<public> : float = ${priceFloat}\n`;
  }
  out += `\n`;

  // 5. Offers Module
  out += `# ====================================================================\n`;
  out += `# 4. Offers Module\n`;
  out += `# ====================================================================\n`;
  out += `${offersModule}<public> := module:\n`;
  out += `    using {${infoModule}}\n\n`;

  for (const item of entitlements) {
    const offerClass = `${item.verseKey}_offer`;
    const infoRef = `${infoModule}.${toPascalCase(item.verseKey)}`;
    const textureRef = formatTexture(item.iconTexture, item.verseKey);
    const entRef = `${entModule}.${item.verseKey}_entitlement`;
    const priceRef = `${priceModule}.${toPascalCase(item.verseKey)}`;

    out += `    ${offerClass}<public> := class(entitlement_offer):\n`;
    out += `        var Name<override>:message                = ${infoRef}.Name\n`;
    out += `        var Description<override>:message         = ${infoRef}.Description\n`;
    out += `        var ShortDescription<override>:message    = ${infoRef}.ShortDescription\n`;
    out += `        var Icon<override>:texture                = ${textureRef}\n`;
    out += `        EntitlementType<override>:concrete_subtype(entitlement) = ${entRef}\n`;
    out += `        Price<override>:price_dimension = MakePriceVBucks(${priceRef})\n`;

    if (item.ageAndRegion.enabled && item.ageAndRegion.minAge > 0) {
      out += `        GetMinPurchaseAge<override>(CountryCode:string, SubdivisionCode:string, PlatformFamily:string)<decides><computes>:int =\n`;
      if (item.ageAndRegion.allowedCountryCodes.length > 0) {
        const countryChecks = item.ageAndRegion.allowedCountryCodes
          .map(cc => `CountryCode = "${cc}"`)
          .join(' or ');
        out += `            (${countryChecks})\n`;
      }
      out += `            return ${item.ageAndRegion.minAge}\n`;
    }
    out += `\n`;
  }

  for (const bundle of bundles) {
    const bundleClass = `${bundle.verseKey}_offer`;
    const infoRef = `${infoModule}.${toPascalCase(bundle.verseKey)}`;
    const textureRef = formatTexture(bundle.iconTexture, bundle.verseKey);
    const priceRef = `${priceModule}.${toPascalCase(bundle.verseKey)}`;

    out += `    ${bundleClass}<public> := class(bundle_offer):\n`;
    out += `        var Name<override>:message                = ${infoRef}.Name\n`;
    out += `        var Description<override>:message         = ${infoRef}.Description\n`;
    out += `        var ShortDescription<override>:message    = ${infoRef}.ShortDescription\n`;
    out += `        var Icon<override>:texture                = ${textureRef}\n`;
    
    const offerTuples = bundle.items.map(bItem => {
      const parentEnt = entitlements.find(e => e.id === bItem.entitlementId);
      const offerName = parentEnt ? `${parentEnt.verseKey}_offer{}` : 'basic_sword{}';
      return `(${offerName}, ${bItem.quantity || 1})`;
    }).join(', ');

    out += `        Offers<override>:[]tuple(offer, int) = array{${offerTuples}}\n`;
    out += `        Price<override>:price_dimension = MakePriceVBucks(${priceRef})\n\n`;
  }

  // 6. Creative Device Class
  out += `# ====================================================================\n`;
  out += `# 5. In-Island Transactions Creative Device\n`;
  out += `# ====================================================================\n`;
  out += `${deviceClass} := class(creative_device):\n\n`;
  out += `    # Per-player entitlement change subscription tracking\n`;
  out += `    var EntitlementChangeSubscription:[player]?cancelable = map{}\n`;
  out += `    var PlayerJoinSubscription:?cancelable = false\n`;
  out += `    var PlayerLeftSubscription:?cancelable = false\n\n`;

  // Custom Lifecycle Events
  out += `    # Built-in Lifecycle Events\n`;
  out += `    PurchaseCancelledEvent<public> : event(tuple(player, string)) = event(tuple(player, string)){}\n`;
  out += `    PurchaseCompletedEvent<public> : event(tuple(player, string, int)) = event(tuple(player, string, int)){}\n\n`;

  // Collect any signal_event custom events
  const customEvents = entitlements
    .filter(e => e.actionHook.type === 'signal_event' && e.actionHook.eventName)
    .map(e => e.actionHook.eventName!);
  const uniqueCustomEvents = Array.from(new Set(customEvents));

  for (const evt of uniqueCustomEvents) {
    out += `    ${evt}<public> : event(player) = event(player){}\n`;
  }
  if (uniqueCustomEvents.length > 0) out += `\n`;

  // Editable device references
  const buttonBindings = entitlements.filter(e => e.triggers.generateButtonBinding && e.triggers.buttonDeviceName);
  const zoneBindings = entitlements.filter(e => e.triggers.generateZoneBinding && e.triggers.mutatorZoneName);

  for (const b of buttonBindings) {
    out += `    @editable ${b.triggers.buttonDeviceName} : []button_device = array{}\n`;
  }
  for (const z of zoneBindings) {
    out += `    @editable ${z.triggers.mutatorZoneName} : []mutator_zone_device = array{}\n`;
  }
  if (buttonBindings.length > 0 || zoneBindings.length > 0) out += `\n`;

  // OnBegin
  out += `    OnBegin<override>()<suspends>:void =\n`;
  out += `        SubJoin := GetPlayspace().PlayerAddedEvent().Subscribe(OnPlayerJoin)\n`;
  out += `        set PlayerJoinSubscription = option{ SubJoin }\n\n`;
  out += `        SubLeft := GetPlayspace().PlayerRemovedEvent().Subscribe(OnPlayerLeft)\n`;
  out += `        set PlayerLeftSubscription = option{ SubLeft }\n\n`;
  out += `        Players := GetPlayspace().GetPlayers()\n`;
  out += `        for (Player : Players):\n`;
  out += `            GetEntitlementsChangedEvent(Player, ${entModule}.basic_entitlement).Subscribe(OnPurchasesChanged)\n`;
  out += `            spawn{ ValidatePreviousPurchases(Player) }\n\n`;

  // Wire Button triggers
  for (const b of buttonBindings) {
    const promptFunc = `Prompt${toPascalCase(b.verseKey)}`;
    out += `        for (Button : ${b.triggers.buttonDeviceName}):\n`;
    out += `            Button.InteractedWithEvent.Subscribe(${promptFunc})\n`;
  }

  // Wire Zone triggers
  for (const z of zoneBindings) {
    const zonePromptFunc = `OnZoneEntered${toPascalCase(z.verseKey)}`;
    out += `        for (Zone : ${z.triggers.mutatorZoneName}):\n`;
    out += `            Zone.AgentEntersEvent.Subscribe(${zonePromptFunc})\n`;
  }

  // Spawn async listeners
  const asyncListeners = entitlements.filter(e => e.triggers.generateAsyncListener && e.triggers.asyncEventName);
  for (const a of asyncListeners) {
    out += `        spawn{ ListenFor${toPascalCase(a.verseKey)}Prompts() }\n`;
  }

  out += `\n`;

  // OnEnd
  out += `    OnEnd<override>() : void =\n`;
  out += `        if (Sub := PlayerJoinSubscription?) { Sub.Cancel() }\n`;
  out += `        if (Sub := PlayerLeftSubscription?) { Sub.Cancel() }\n\n`;

  // OnPlayerJoin & OnPlayerLeft
  out += `    OnPlayerJoin(InPlayer:player):void =\n`;
  out += `        Subscription := GetEntitlementsChangedEvent(InPlayer, ${entModule}.basic_entitlement).Subscribe(OnPurchasesChanged)\n`;
  out += `        if (set EntitlementChangeSubscription[InPlayer] = option{Subscription}):\n`;
  out += `            Print("[IIT] Subscribed player to entitlement changes.")\n`;
  out += `        spawn{ ValidatePreviousPurchases(InPlayer) }\n\n`;

  out += `    OnPlayerLeft(Player:player):void =\n`;
  out += `        if (Subscription := EntitlementChangeSubscription[Player]?):\n`;
  out += `            Subscription.Cancel()\n`;
  out += `        var TempMap:[player]?cancelable = map{}\n`;
  out += `        for (Key -> Value : EntitlementChangeSubscription, Key <> Player):\n`;
  out += `            set TempMap = ConcatenateMaps(TempMap, map{Key => Value})\n`;
  out += `        set EntitlementChangeSubscription = TempMap\n\n`;

  // OnPurchasesChanged
  out += `    # Authoritative Purchase & Entitlement Change Handler\n`;
  out += `    OnPurchasesChanged(Player:player, EntitlementChanges:[]entitlement_change(entitlement)):void =\n`;
  out += `        Print("[IIT] Processing Entitlement Changes for Player")\n`;
  out += `        for (EntChange : EntitlementChanges, Ent := EntChange.Entitlement):\n`;
  out += `            if (EntChange.Quantity > 0):\n`;
  out += `                PurchaseCompletedEvent.Signal((Player, "${entModule}", EntChange.Quantity))\n\n`;

  let isFirstBranch = true;
  for (const item of entitlements) {
    const cond = isFirstBranch ? 'if' : 'else if';
    isFirstBranch = false;
    const entClass = `${entModule}.${item.verseKey}_entitlement`;
    const procFunc = `Process${toPascalCase(item.verseKey)}Purchase`;

    out += `                ${cond} (${entClass}[Ent]):\n`;
    out += `                    spawn{ ${procFunc}(Player, ${entClass}, EntChange.Quantity) }\n`;
  }
  out += `\n`;

  // Reward Processors
  for (const item of entitlements) {
    const procFunc = `Process${toPascalCase(item.verseKey)}Purchase`;
    const isConsumable = item.itemType === 'consumable';
    const autoConsume = item.autoConsume;

    out += `    ${procFunc}(Player:player, EntType:concrete_subtype(entitlement), QuantityBought:int)<suspends>:void =\n`;
    out += `        Print("[IIT] Granted ${escapeVerseString(item.name)} x{QuantityBought}")\n`;

    // Action hook logic
    if (item.actionHook.type === 'signal_event' && item.actionHook.eventName) {
      out += `        ${item.actionHook.eventName}.Signal(Player)\n`;
    } else if (item.actionHook.type === 'device_method' && item.actionHook.targetDevice) {
      out += `        ${item.actionHook.targetDevice}\n`;
    } else if (item.actionHook.type === 'custom_verse' && item.actionHook.customVerseCode) {
      const indented = item.actionHook.customVerseCode
        .split('\n')
        .map(l => `        ${l}`)
        .join('\n');
      out += `${indented}\n`;
    }

    // Auto-consume if applicable
    if (isConsumable && autoConsume) {
      out += `        TryConsumeEntitlement(Player, EntType, QuantityBought)\n`;
    }
    out += `\n`;
  }

  // Prompt functions
  for (const item of entitlements) {
    const promptFunc = `Prompt${toPascalCase(item.verseKey)}`;
    const offerRef = `${offersModule}.${item.verseKey}_offer{}`;

    out += `    ${promptFunc}<public>(Agent:agent):void =\n`;
    out += `        if (P := player[Agent]):\n`;
    out += `            spawn{ TryBuyOffer(P, ${offerRef}) }\n\n`;
  }

  // Mutator Zone handlers
  for (const z of zoneBindings) {
    const zoneFunc = `OnZoneEntered${toPascalCase(z.verseKey)}`;
    const promptFunc = `Prompt${toPascalCase(z.verseKey)}`;

    out += `    ${zoneFunc}(Agent:agent):void =\n`;
    out += `        if (P := player[Agent]):\n`;
    if (z.itemType === 'durable') {
      out += `            # Check if player already owns it\n`;
      out += `            OwnedList := GetPurchasedEntitlements(P, ${entModule}.${z.verseKey}_entitlement)\n`;
      out += `            if (Owned := OwnedList[0], Owned(1) > 0):\n`;
      out += `                Print("[IIT] Player already owns ${escapeVerseString(z.name)}, skipping zone prompt")\n`;
      out += `            else:\n`;
      out += `                ${promptFunc}(Agent)\n`;
    } else {
      out += `            ${promptFunc}(Agent)\n`;
    }
    out += `\n`;
  }

  // Async listeners
  for (const a of asyncListeners) {
    const listenFunc = `ListenFor${toPascalCase(a.verseKey)}Prompts`;
    const promptFunc = `Prompt${toPascalCase(a.verseKey)}`;

    out += `    ${listenFunc}()<suspends>:void =\n`;
    out += `        loop:\n`;
    out += `            Agent := ${a.triggers.asyncEventName}.Await()\n`;
    out += `            ${promptFunc}(Agent)\n\n`;
  }

  // Validation on Rejoin (ValidatePreviousPurchases)
  out += `    # Player Reconnection & Save Validation\n`;
  out += `    ValidatePreviousPurchases(Player:player)<suspends>:void =\n`;
  out += `        Print("[IIT] Validating previous purchases on player join...")\n`;

  const durables = entitlements.filter(e => e.itemType === 'durable');
  for (const d of durables) {
    const entClass = `${entModule}.${d.verseKey}_entitlement`;
    out += `        Purchased_${toPascalCase(d.verseKey)} := GetPurchasedEntitlements(Player, ${entClass})\n`;
    out += `        if (Owned := Purchased_${toPascalCase(d.verseKey)}[0], Owned(1) > 0):\n`;
    out += `            Print("[IIT] Player verified owner of ${escapeVerseString(d.name)}")\n`;
    if (d.rejoinHook.autoRestore && d.rejoinHook.customVerificationCode) {
      const indented = d.rejoinHook.customVerificationCode
        .split('\n')
        .map(l => `            ${l}`)
        .join('\n');
      out += `${indented}\n`;
    } else if (d.actionHook.type === 'signal_event' && d.actionHook.eventName) {
      out += `            ${d.actionHook.eventName}.Signal(Player)\n`;
    }
  }
  out += `\n`;

  // Core Marketplace API Wrappers (TryBuyOffer with cancellation handling, TryConsume, TryGrant)
  out += `    # --------------------------------------------------------------------\n`;
  out += `    # Core Marketplace Operations & Cancellation Detection\n`;
  out += `    # --------------------------------------------------------------------\n`;
  out += `    TryBuyOffer(Player:player, Offer:entitlement_offer)<suspends>:void =\n`;
  out += `        Result := BuyOffer(Player, Offer)\n`;
  out += `        if (Result?):\n`;
  out += `            # Purchase initiated; reward is handled asynchronously via OnPurchasesChanged\n`;
  out += `            Print("[IIT] BuyOffer dialog confirmed by player")\n`;
  out += `        else:\n`;
  out += `            # Player cancelled the purchase dialog or dialog failed to load\n`;
  out += `            Print("[IIT] Player cancelled purchase or offer failed to display.")\n`;
  out += `            PurchaseCancelledEvent.Signal((Player, "OfferCancelled"))\n\n`;

  out += `    TryConsumeEntitlement(Player:player, Entitlement:concrete_subtype(entitlement), NumberConsuming:int)<suspends>:void =\n`;
  out += `        Result := ConsumeEntitlement(Player, Entitlement, ?Count := NumberConsuming)\n`;
  out += `        if (Result?):\n`;
  out += `            Print("[IIT] Successfully consumed entitlement ({NumberConsuming} units).")\n`;
  out += `        else:\n`;
  out += `            Print("[IIT] Failed to consume entitlement.")\n\n`;

  out += `    TryGrantEntitlement(Player:player, Entitlement:concrete_subtype(entitlement), NumberToGrant:int)<suspends>:void =\n`;
  out += `        Result := GrantEntitlement(Player, Entitlement, ?Count := NumberToGrant)\n`;
  out += `        if (Result?):\n`;
  out += `            Print("[IIT] Successfully granted entitlement ({NumberToGrant} units).")\n`;
  out += `        else:\n`;
  out += `            Print("[IIT] Failed to grant entitlement.")\n\n`;

  return out;
}
