import { EntitlementItem, BundleOffer } from '../types/entitlement';

export const DEFAULT_PRESETS: Partial<EntitlementItem>[] = [
  {
    name: 'VIP Pass',
    verseKey: 'vip_pass',
    shortDescription: '⭐ Unlock exclusive VIP conveyors & special overhead badge!',
    description: 'Grants access to the exclusive VIP block conveyors and shows a special VIP badge above your head!',
    priceVBucks: 500,
    itemType: 'durable',
    maxCount: 1,
    autoConsume: false,
    iconTexture: 'EntitlementIcons.Icon_VIP',
    flags: {
      paidRandomItem: false,
      paidRandomItemOdds: '',
      paidArea: true,
      consequentialToGameplay: true,
    },
    ageAndRegion: {
      enabled: false,
      minAge: 0,
      allowedCountryCodes: [],
      disallowedCountryCodes: [],
    },
    actionHook: {
      type: 'signal_event',
      eventName: 'VipPassPurchasedEvent',
    },
    cancelHook: {
      notifyPlayer: true,
      notificationMessage: 'VIP Pass purchase was cancelled.',
    },
    rejoinHook: {
      autoRestore: true,
      customVerificationCode: '# Verify VIP pass on reconnect and fire event if owned\nVipPassPurchasedEvent.Signal(Player)',
    },
    triggers: {
      generateButtonBinding: true,
      buttonDeviceName: 'VipPassButtons',
      generateZoneBinding: true,
      mutatorZoneName: 'VipPassZones',
      generateAsyncListener: false,
    },
  },
  {
    name: '+10 Strength Boost',
    verseKey: 'strength_boost_10',
    shortDescription: '🔥 10 Levels of Strength - TOSS YOUR BLOCKS FURTHER!',
    description: 'Consumable boost giving 10 strength levels instantly to fling items with incredible power!',
    priceVBucks: 150,
    itemType: 'consumable',
    maxCount: 5,
    autoConsume: true,
    iconTexture: 'EntitlementIcons.Strength_10',
    flags: {
      paidRandomItem: false,
      paidRandomItemOdds: '',
      paidArea: false,
      consequentialToGameplay: true,
    },
    ageAndRegion: {
      enabled: false,
      minAge: 0,
      allowedCountryCodes: [],
      disallowedCountryCodes: [],
    },
    actionHook: {
      type: 'grant_stat',
      statName: 'StrengthLevels',
      statAmount: 10,
      targetDevice: 'ShopManager.GrantFreeUpgradeToss(Player, 10 * QuantityBought)',
    },
    cancelHook: {
      notifyPlayer: false,
    },
    rejoinHook: {
      autoRestore: false,
    },
    triggers: {
      generateButtonBinding: false,
      generateZoneBinding: false,
      generateAsyncListener: true,
      asyncEventName: 'UIManager.TossUpgradeIITEvent',
    },
  },
  {
    name: '2x Cash Multiplier',
    verseKey: 'double_money',
    shortDescription: '🔥🤑 Permanent 2x Cash Multiplier on all earnings!',
    description: 'Permanently doubles all currency earned across your gameplay sessions!',
    priceVBucks: 400,
    itemType: 'durable',
    maxCount: 1,
    autoConsume: false,
    iconTexture: 'EntitlementIcons.Double_Cash',
    flags: {
      paidRandomItem: false,
      paidRandomItemOdds: '',
      paidArea: false,
      consequentialToGameplay: true,
    },
    ageAndRegion: {
      enabled: false,
      minAge: 0,
      allowedCountryCodes: [],
      disallowedCountryCodes: [],
    },
    actionHook: {
      type: 'device_method',
      targetDevice: 'SaveManager.GrantDoubleMoney(Player)',
    },
    cancelHook: {
      notifyPlayer: false,
    },
    rejoinHook: {
      autoRestore: true,
      customVerificationCode: 'SaveManager.GrantDoubleMoney(Player)',
    },
    triggers: {
      generateButtonBinding: true,
      buttonDeviceName: 'DoubleMoneyButtons',
      generateZoneBinding: false,
      generateAsyncListener: false,
    },
  },
  {
    name: 'Mystery Crate (Random Reward)',
    verseKey: 'mystery_crate',
    shortDescription: '🎲 Open a mystery crate containing rare or legendary loot!',
    description: 'Spin for randomized items! Odds: Common (60%), Rare (30%), Epic (8%), Legendary (2%).',
    priceVBucks: 100,
    itemType: 'consumable',
    maxCount: 10,
    autoConsume: true,
    iconTexture: 'EntitlementIcons.MysteryCrate',
    flags: {
      paidRandomItem: true,
      paidRandomItemOdds: 'Common: 60%, Rare: 30%, Epic: 8%, Legendary: 2%',
      paidArea: false,
      consequentialToGameplay: true,
    },
    ageAndRegion: {
      enabled: false,
      minAge: 0,
      allowedCountryCodes: [],
      disallowedCountryCodes: [],
    },
    actionHook: {
      type: 'custom_verse',
      customVerseCode: '# Trigger RNG Loot Roll for the player\nRNGManager.RollMysteryCrate(Player, QuantityBought)',
    },
    cancelHook: {
      notifyPlayer: true,
      notificationMessage: 'Crate purchase cancelled.',
    },
    rejoinHook: {
      autoRestore: false,
    },
    triggers: {
      generateButtonBinding: false,
      generateZoneBinding: false,
      generateAsyncListener: true,
      asyncEventName: 'UIManager.MysteryCrateIITEvent',
    },
  },
  {
    name: '+10 Backpack Slots',
    verseKey: 'bag_expansion_10',
    shortDescription: '🎒 Instantly expand your inventory capacity by +10 slots!',
    description: 'Permanently adds 10 extra storage slots to your inventory. Caps at +70 slots.',
    priceVBucks: 100,
    itemType: 'consumable',
    maxCount: 7,
    autoConsume: true,
    iconTexture: 'EntitlementIcons.Inventory_10',
    flags: {
      paidRandomItem: false,
      paidRandomItemOdds: '',
      paidArea: false,
      consequentialToGameplay: true,
    },
    ageAndRegion: {
      enabled: false,
      minAge: 0,
      allowedCountryCodes: [],
      disallowedCountryCodes: [],
    },
    actionHook: {
      type: 'device_method',
      targetDevice: 'SaveManager.GrantPurchasedInventorySlots(Player, 10 * QuantityBought)',
    },
    cancelHook: {
      notifyPlayer: false,
    },
    rejoinHook: {
      autoRestore: false,
    },
    triggers: {
      generateButtonBinding: false,
      generateZoneBinding: false,
      generateAsyncListener: true,
      asyncEventName: 'UIManager.InvIITEvent',
    },
  },
];
